### ISSUE TITLE
@ryanderickson - SSL error while cloning repo 

### ISSUE THREAD

**Issue by froi** [department-of-veterans-affairs/ncod-all-employee-survey#1]
Hello @ryanderickson,

You've reported the following error while trying to clone this repo:

```
fatal: unable to access 'https://github.com/department-of-veterans-affairs/ncod-all-employee-survey.git/': error:1425F175:SSL routines:ssl_choose_client_version:inappropriate fallback
```

I'd like a better understanding of your setup to see how best I can help.

1. What OS are you using?
2. How are you trying to do the clone of the repo (command line, Github Desktop app, other)?
   1. Have you tried using the [Github Desktop app](https://desktop.github.com/)?

cc: @elstudio

**Comment by ryanderickson** [comment]
Hi, thanks for the help.

Using Windows 7. I’ve tried through the RStudio IDE (it’s something like Vim, etc. for R). Got the same error trying in git bash, so the error is w/git not w/RStudio.

**Comment by ryanderickson** [comment]
Hi,

Using Windows 7. I tried to clone through RStudio (an IDE for R) and in git bash, received the same error in both.

**Comment by froi** [comment]
Thanks for the info @ryanderickson. I'm going to do some research real quick to see what options are available to work with this problem.

One more thing. You mentioned that somebody had help you access an internal repository and that the process was "semi-involved". Could I get the detail of that as well via email? I just want to make sure that we don't break anything that is working for you.

Thanks!

**Comment by ryanderickson** [comment]
Attached.

The background is, I have a development space in the Azure lab. The team that set that up created a github for me on the github.ec.va.gov version – the attached email shows what I had to do to get access to that. That one works for me now but it’s not accessible to people outside the VA’s network, so that’s why I made the request that you saw.

**Comment by froi** [comment]
Thanks for all the info and sorry for all of this back and forth.

We've got some ideas but need a bit more info to narrow things down. Could you tell me:

1. Are you trying to access the repository on a VA network?
2. Is the computer you are using VA equipment?
3.  Can you install Github Desktop and try to clone using this application?

If you can't install Github Desktop or if you get the same error could you tell me:

1. What version of git bash are you using?
2. What version of R Studio did you use?
3. Can you access this repo from your browser?
4. What browser are you using?

Thank you for your patience and for providing all of this information. It will help us rule out scenarios and make sure that this doesn't affect other of our VA colleagues.

**Comment by ryanderickson** [comment]
So, I was able to clone it using github desktop and I tried it again in bash and this time it worked, I was able to clone & push a change. So it appears it’s working now for whatever reason.

Now the problem is with RStudio… it works when I clone using RStudio’s interface also but now the RStudio git tab that has the commit, push, etc. functions has just disappeared. Strange, because it worked fine when I cloned/committed/pushed to the other github on the azure lab space.  I realize this is probably a RStudio issue so I’m happy to try and resolve it myself if that’s outside the scope of what this support is for… the actual git part is working at least. Really appreciate the help. Answering your questions anyway below:

Yes, VA network/VA equipment
Git 2.20.1, just downloaded it a few weeks ago
RStudio 1.1.463 I think… “check for update” says it’s the most recent version.

**Comment by froi** [comment]
I'm glad that using the Github Desktop app helped you solve your issues with the repo. I'm not 100% sure as to why using the Github Desktop app helped but I will keep an eye out for any answer that can help. 

As for RStudio, it's my understanding that it is outside of the scope for our support. I would reach out to them for any questions as to why this might have occurred.

I'll be closing this issue but please reach out with any other question or problem you might have.
